- name: Check and install security updates
  yum:
    security: yes
    state: latest
  check_mode: yes
  register: yum_output
  become: true

- name: show that yum output
  debug:
    var: yum_output