---
- name: Download Satellite Capsule config
  uri:
    url: https://{{ sat_capsule }}/pub/katello-ca-consumer-latest.noarch.rpm
    validate_certs: no
    dest: /tmp/

- name: Install Satellite Capsule katello-ca config
  yum:
    name: /tmp/katello-ca-consumer-latest.noarch.rpm
    state: present

- name: Set Satellite config to no_proxy
  command: subscription-manager config --server.no_proxy=*
  args:
    warn: no

- name: Register host with activationkey
  redhat_subscription:
    state: present
    activationkey: "{{ sat_key }}"
    org_id: "{{ sat_org }}"

- name: Remove rpm file
  file:
    path: /tmp/katello-ca-consumer-latest.noarch.rpm
    state: absent