---
- name: Download and install Satellite Capsule config
  shell: |
    curl --insecure --output katello-ca-consumer-latest.noarch.rpm https://"{{ sat_capsule }}"/pub/katello-ca-consumer-latest.noarch.rpm
    yum localinstall -y katello-ca-consumer-latest.noarch.rpm

- name: Register host to Satellite Capsule
  shell: |
    subscription-manager config --server.no_proxy=*
    subscription-manager register --org="{{ sat_org }}" --activationkey="{{ sat_key }}"

