---
- hosts: marklogic_all
  become: true
  roles:
  - marklogic_install

- hosts: "{{ ml_master }}"
  become: true
  roles:
  - marklogic_create_cluster

- hosts: marklogic_all:!"{{ ml_master }}"
  become: true
  roles:
  - marklogic_join_cluster