---
- hosts: [marklogic]
  become: true
  roles:
  - marklogic_install

- hosts: [mlmaster]
  become: true
  roles:
  - marklogic_create_cluster

- hosts: [mlslave]
  become: true
  roles:
  - marklogic_join_cluster