---
# handlers file for roles/base
- name: restart sshd
  service:
    name: sshd
    state: restarted
- name: restart ntpd
  service:
    name: ntpd
    state: restarted
- name: restart chronyd
  service:
    name: chronyd
    state: restarted