- name: Print hostname
  ansible.builtin.debug:
    var: {{ ansible_facts['nodename'] }}
  
- name: Print IP info
  ansible.builtin.debug:
    var: {{ ansible_facts['all_ipv4_addresses'] }}

- name: Print cpu count
  ansible.builtin.debug:
    var: {{ ansible_facts['processor_nproc'] }}

- name: Print disk info
  ansible.builtin.debug:
    var: {{ ansible_facts['mounts'][0]['size_total'] }}