- name: Print hostname
  debug:
    msg: "{{ ansible_nodename}}"
  
- name: Print IP info
  debug:
    msg: "{{ ansible_default_ipv4.address }}"

- name: Print memory info
  debug:
    msg: "{{ ansible_memtotal_mb }}"

- name: Print number cpus
  debug:
    msg: "{{ ansible_processor_vcpus }}"

- name: Print disk info
  debug:
    msg: "{{ item.size_total }}"
  loop: "{{ ansible_mounts }}"
    # msg: "{{ ansible_facts['mounts'][0]['size_total'] }}"    

