- name: Add the user 'ansible'
  user:
    name: ansible
    comment: Ansible user
    # uid: 2000
    group: dst
    generate_ssh_key: no

- name: Set authorized keys from file
  authorized_key:
    user: ansible
    state: present
    key: '{{ item }}'
  with_file:
  - ansible.keys