---
- name: Create Host and add to DST Inventory
  tower_host:
    inventory: "{{ dst_inventory }}"
    name: "{{ hostname }}"
    description: "{{ host_desc }}"
    state: present
  register: created_host

- name: Add created host to selected group
  shell: tower-cli host associate  --host "{{ created_host.id }}" --group "{{ selected_group }}" --insecure