---
- name: Unregister host
  redhat_subscription:
    state: absent

- name: subscription-manager-clean
  command: subscription-manager clean
  args:
    warn: no

- name: Remove the Satellite katello-ca-consumer package
  yum:
    name: katello-ca-consumer-rhsat.bbc.co.uk.noarch
    state: absent

- name: yum-clean-all
  command: yum clean all
  args:
    warn: no
  ignore_errors: yes