---
- name: Create mysql group
  group:
    state: present
    name: "mysql"
    gid: 8004

- name: Create mysql user
  user:
    name: mysql
    uid: 8004
    group: mysql
    state: present

- name: "Create /data/mysql directory"
  file:
    path: /data/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'